set-option -g default-terminal 'screen-256color'
set-option -g terminal-override ',xterm-256colo:RGB'


set -g base-index 1
set -g history-limit 100000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
setw -g mode-keys vi

bind-key r source-file ~/tmux.conf \; display-message "~/tmux.conf reloaded"
